### ISSUE TITLE
cldi单元测试偶尔会失败

### ISSUE THREAD

**Issue by rink1969** [cita-cloud/cloud-cli#85]
偶尔报错：
```
thread 'cmd::admin::tests::test_admin_subcmds' panicked at 'MockControllerClient::connect_lazy(?, ?): No matching expectation found', src/core/mock.rs:41:1
```

**Comment by rink1969** [comment]
调用栈：
```
  21:     0x560e3ab28f7a - core::option::Option<T>::expect::hb74ffa9e71e85808
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:786:21
  22:     0x560e3ace5c66 - <cldi::core::mock::MockControllerClient as cldi::core::client::GrpcClientBehaviour>::connect_lazy::h7703036b65758cd3
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/core/mock.rs:41:1
  23:     0x560e3aaf6027 - cldi::core::context::Context<Co,Ex,Ev>::from_config::{{closure}}::h643bb3c034affa41
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/core/context.rs:66:22
  24:     0x560e3ab04744 - cldi::core::context::CtrlCSignalCapturedRuntime::block_on::{{closure}}::{{closure}}::h05d1b8e8beae305b
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/macros/select.rs:517:49
  25:     0x560e3a9cbfbf - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h6659537955521857
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/future/poll_fn.rs:58:9
  26:     0x560e3ab012d4 - cldi::core::context::CtrlCSignalCapturedRuntime::block_on::{{closure}}::hd250a9bb351f373d
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/core/context.rs:172:13
  27:     0x560e3aa6d593 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::hf7a830afa106aa5b
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/park.rs:283:63
  28:     0x560e3aa661b7 - tokio::runtime::coop::with_budget::h640b89243d77f6e9
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:107:5
  29:     0x560e3aa661b7 - tokio::runtime::coop::budget::h30d28a59c4a5f93e
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:73:5
  30:     0x560e3aa661b7 - tokio::runtime::park::CachedParkThread::block_on::h9eccd91eeac34646
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/park.rs:283:31
  31:     0x560e3aa24e64 - tokio::runtime::context::BlockingRegionGuard::block_on::h5b1f80ea72575e92
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/context.rs:315:13
  32:     0x560e3ac1c3d2 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h756828585d1b3078
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  33:     0x560e3aa14248 - tokio::runtime::runtime::Runtime::block_on::h66c1c00bcc944fb4
                               at /home/rink/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/runtime.rs:304:45
  34:     0x560e3aaf78a2 - cldi::core::context::CtrlCSignalCapturedRuntime::block_on::h00c1b5f722e1edcb
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/core/context.rs:171:9
  35:     0x560e3aaf5a4e - cldi::core::context::Context<Co,Ex,Ev>::from_config::h6093187f066ff2e6
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/core/context.rs:65:43
  36:     0x560e3ace3ffa - cldi::core::mock::context::hfcf92ba447cb2ac5
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/core/mock.rs:181:19
  37:     0x560e3a9949b7 - cldi::cmd::rpc::tests::test_rpc_subcmds::h2407b0645ee33498
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/cmd/rpc.rs:519:36
  38:     0x560e3a9c43d7 - cldi::cmd::rpc::tests::test_rpc_subcmds::{{closure}}::h728c8fbcfac1df7f
                               at /home/rink/work/github/cita-cloud/cloud-cli/src/cmd/rpc.rs:517:27

```

相关代码(把mock宏展开后)：
```
  fn connect_lazy(addr: &str,dur:Duration) -> Result<MockControllerClient>{
    let no_match_msg = std::format!("{}: No matching expectation found",std::format!("MockControllerClient::connect_lazy({:?}, {:?})", ::mockall::MaybeDebugger(&addr), ::mockall::MaybeDebugger(&dur)));
    {
      let __mockall_guard = __mock_MockControllerClient_GrpcClientBehaviour::__connect_lazy::EXPECTATIONS.lock().unwrap();
      __mockall_guard.call(addr,dur,)
    }.expect(&no_match_msg)
  }
```
可以看到这里获取锁没有成功，才会打印相关的报错信息
可能是跟cargo test 默认是并行执行的有关
增加参数让cargo test串行
```
cargo test -j 1
```

**Comment by rink1969** [comment]
不是并行的问题
参考 https://github.com/asomers/mockall/issues/424
相关函数不用mock宏实现，而是自己单独实现。
